{% set name = "pdf-core" %}
{% set version = "0.10.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: 0a5d101e2063c01e3f941e1ee47cbb97f1adfc1395b58372f4f65f1300f3ce91

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r pdf/core -e 'exit 0'

about:
  home: https://prawnpdf.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: 
    - LICENSE
    - GPLv2
    - GPLv3
  summary: |
    PDF::Core is used by Prawn to render PDF documents
  description:
  doc_url: https://prawnpdf.org/docs/pdf-core
  dev_url: https://github.com/prawnpdf/pdf-core

extra:
  recipe-maintainers:
    - jdmarques
